name: Docker-login
on: workflow_dispatch

jobs:
#using prebuild login
  Docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          # Username used to log against the Docker registry
          username: ${{var.DOCKER_USERNAME}}
          # Password or personal access token used to log against the Docker registry
          password: ${{secrets.DOCKER_PWD}}
#using manual login
  Docker-manual-login:
    runs-on: ubuntu-latest
    steps:
      - name: manual-login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
